---
title: "eda"
output: github_document
---

```{r}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


load in a dataset
```{r}
weather_df =  
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, everything())
```


## `group_by`

```{r}
weather_df %>% 
  group_by(name, month)
```

## count some things
```{r}
weather_df %>% 
  group_by(month) %>%   ## group by `month`
  summarize(n_obs = n())  ## count the number of obs in each group.


weather_df %>% 
  count(name)  ## easy way to do.
```

It is nice that summarize produces a data frame.
`table` doesn't and that's bad

```{r}
weather_df %>% 
  pull(name) %>% 
  table()
```
This is a good way to do it!
```{r}
weather_df %>% 
  janitor::tabyl(month, name)
```

## More general summaries.
Count, means, SDs
```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(
    n_obs = n(),
    mean_tmax = mean(tmax, na.rm = TRUE),  ## removing missing values
    median_tmax = median(tmax, na.rm = TRUE),
    sd_tmax = sd(tmax, na.rm = TRUE)
  ) %>% 
  ggplot(aes(x = month, y = mean_tmax, color = name)) +
  geom_point() +
  geom_line()
```

`knitr::kable` is useful!
```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(
    n_obs = n(),
    mean_tmax = mean(tmax, na.rm = TRUE),  ## removing missing values
    median_tmax = median(tmax, na.rm = TRUE),
    sd_tmax = sd(tmax, na.rm = TRUE)
  ) %>% 
  knitr::kable(digits = 2) ## this can make your table more readable when knitting your rmd
```


## grouped `mutate`

`group by` and `mutate`

```{r}
weather_df %>% 
  group_by(name) %>% 
  mutate(
    mean_tmax = mean(tmax, na.rm = TRUE), ## if you `group` and then `mutate`, it calculated in each group.
    centered_tmax = tmax - mean_tmax, 
  ) %>% 
  ggplot(aes(x = date, y = centered_tmax, color = name)) +
  geom_point()
```

**Windowed rank functions**
```{r}
weather_df %>% 
  group_by(name) %>% 
  mutate(
    tmax_rank = min_rank(desc(tmax)) ## it's a group width mean because we group by name.
    ## `desc()` Transform a vector into a format that will be sorted in descending order.
  ) %>% 
  filter(tmax_rank < 2)
```

**Lagged** variables

```{r}
weather_df %>% 
  group_by(name) %>% 
  mutate(
    lagged_tmax = lag(tmax, n = 1), ## what is the tmax of yesterday.
    tmax_diff = tmax - lagged_tmax ## what is the change between 2 days.
  ) %>% 
  summarize(diff_sd = sd(tmax_diff, na.rm = TRUE))
  
```

## Limitations

What if my "summary" is a linear model...

```{r}
weather_df %>% 
  group_by(name) %>% 
  summarize(cor_tmin_tmax = cor(tmin, tmax, use = "complete"))
            
weather_df %>% 
  filter(name == "CentralPark_NY") %>% 
  lm(tmax ~ tmin, data = .)  ## Fitting Linear Models use `lm`


  
  
```

